# VGA CONSTRAINTS
set_property PACKAGE_PIN V18 [get_ports {R_V[3]}]
set_property PACKAGE_PIN V19 [get_ports {R_V[2]}]
set_property PACKAGE_PIN U20 [get_ports {R_V[1]}]
set_property PACKAGE_PIN V20 [get_ports {R_V[0]}]
set_property PACKAGE_PIN AB19 [get_ports {B_V[3]}]
set_property PACKAGE_PIN AB20 [get_ports {B_V[2]}]
set_property PACKAGE_PIN Y20 [get_ports {B_V[1]}]
set_property PACKAGE_PIN Y21 [get_ports {B_V[0]}]
set_property PACKAGE_PIN AA21 [get_ports {G_V[3]}]
set_property PACKAGE_PIN AB21 [get_ports {G_V[2]}]
set_property PACKAGE_PIN AA22 [get_ports {G_V[1]}]
set_property PACKAGE_PIN AB22 [get_ports {G_V[0]}]
set_property PACKAGE_PIN AA19 [get_ports {H_SYNC_V[0]}]
set_property PACKAGE_PIN Y19 [get_ports {V_SYNC_V[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {R_V[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_V[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_V[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_SYNC_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {V_SYNC_V[0]}]

#SWITCH CONSTRAINTS
set_property PACKAGE_PIN F22 [get_ports {selftest[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {selftest[0]}]
set_property PACKAGE_PIN H22 [get_ports ext_reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_gen_25M_23M/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[0]} {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[1]} {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[2]} {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[3]} {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[4]} {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[5]} {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[6]} {design_1_i/pattern_generator_cross_0_outputStream_V_TDATA[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/processing_system7/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 3 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_1_i/axis_to_ddr_writer_frame_index_V[0]} {design_1_i/axis_to_ddr_writer_frame_index_V[1]} {design_1_i/axis_to_ddr_writer_frame_index_V[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/pattern_generator_cross_0_outputStream_V_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/pattern_generator_cross_0_outputStream_V_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out2]
