-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ddr_to_axis_reader is
generic (
    C_M_AXI_BASE_DDR_ADDR_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_BASE_DDR_ADDR_ID_WIDTH : INTEGER := 1;
    C_M_AXI_BASE_DDR_ADDR_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_BASE_DDR_ADDR_DATA_WIDTH : INTEGER := 64;
    C_M_AXI_BASE_DDR_ADDR_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_BASE_DDR_ADDR_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_BASE_DDR_ADDR_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_BASE_DDR_ADDR_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_BASE_DDR_ADDR_USER_VALUE : INTEGER := 0;
    C_M_AXI_BASE_DDR_ADDR_PROT_VALUE : INTEGER := 0;
    C_M_AXI_BASE_DDR_ADDR_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_BASE_DDR_ADDR_TARGET_ADDR : INTEGER := 0 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    outStream_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    outStream_V_TVALID : OUT STD_LOGIC;
    outStream_V_TREADY : IN STD_LOGIC;
    m_axi_base_ddr_addr_AWVALID : OUT STD_LOGIC;
    m_axi_base_ddr_addr_AWREADY : IN STD_LOGIC;
    m_axi_base_ddr_addr_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ADDR_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ID_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_base_ddr_addr_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_base_ddr_addr_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_base_ddr_addr_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_base_ddr_addr_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_base_ddr_addr_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_base_ddr_addr_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_base_ddr_addr_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_base_ddr_addr_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_AWUSER_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_WVALID : OUT STD_LOGIC;
    m_axi_base_ddr_addr_WREADY : IN STD_LOGIC;
    m_axi_base_ddr_addr_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_DATA_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_DATA_WIDTH/8-1 downto 0);
    m_axi_base_ddr_addr_WLAST : OUT STD_LOGIC;
    m_axi_base_ddr_addr_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ID_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_WUSER_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_ARVALID : OUT STD_LOGIC;
    m_axi_base_ddr_addr_ARREADY : IN STD_LOGIC;
    m_axi_base_ddr_addr_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ADDR_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ID_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_base_ddr_addr_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_base_ddr_addr_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_base_ddr_addr_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_base_ddr_addr_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_base_ddr_addr_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_base_ddr_addr_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_base_ddr_addr_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_base_ddr_addr_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ARUSER_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_RVALID : IN STD_LOGIC;
    m_axi_base_ddr_addr_RREADY : OUT STD_LOGIC;
    m_axi_base_ddr_addr_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_DATA_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_RLAST : IN STD_LOGIC;
    m_axi_base_ddr_addr_RID : IN STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ID_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_RUSER_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_base_ddr_addr_BVALID : IN STD_LOGIC;
    m_axi_base_ddr_addr_BREADY : OUT STD_LOGIC;
    m_axi_base_ddr_addr_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_base_ddr_addr_BID : IN STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_ID_WIDTH-1 downto 0);
    m_axi_base_ddr_addr_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BASE_DDR_ADDR_BUSER_WIDTH-1 downto 0);
    frame_index_V : IN STD_LOGIC_VECTOR (2 downto 0);
    frame_count : OUT STD_LOGIC_VECTOR (31 downto 0);
    frame_count_equals : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of ddr_to_axis_reader is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ddr_to_axis_reader,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=346502,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=1,HLS_SYN_FF=882,HLS_SYN_LUT=1493}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_st7_fsm_6 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_st8_fsm_7 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_st9_fsm_8 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_pp0_stg0_fsm_9 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_pp1_stg0_fsm_10 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_st16_fsm_11 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv22_4B000 : STD_LOGIC_VECTOR (21 downto 0) := "0001001011000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv7_4B : STD_LOGIC_VECTOR (6 downto 0) := "1001011";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv7_3F : STD_LOGIC_VECTOR (6 downto 0) := "0111111";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv19_200 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_30 : BOOLEAN;
    signal frame_count_inner : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal index_old : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    signal frame_count_equals_inner : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal base_ddr_addr_AWVALID : STD_LOGIC;
    signal base_ddr_addr_AWREADY : STD_LOGIC;
    signal base_ddr_addr_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal base_ddr_addr_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal base_ddr_addr_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal base_ddr_addr_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal base_ddr_addr_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal base_ddr_addr_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal base_ddr_addr_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal base_ddr_addr_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal base_ddr_addr_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal base_ddr_addr_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_WVALID : STD_LOGIC;
    signal base_ddr_addr_WREADY : STD_LOGIC;
    signal base_ddr_addr_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal base_ddr_addr_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal base_ddr_addr_WLAST : STD_LOGIC;
    signal base_ddr_addr_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_ARVALID : STD_LOGIC;
    signal base_ddr_addr_ARREADY : STD_LOGIC;
    signal base_ddr_addr_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal base_ddr_addr_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal base_ddr_addr_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal base_ddr_addr_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal base_ddr_addr_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal base_ddr_addr_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal base_ddr_addr_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal base_ddr_addr_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal base_ddr_addr_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal base_ddr_addr_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_RVALID : STD_LOGIC;
    signal base_ddr_addr_RREADY : STD_LOGIC;
    signal base_ddr_addr_RDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal base_ddr_addr_RLAST : STD_LOGIC;
    signal base_ddr_addr_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal base_ddr_addr_BVALID : STD_LOGIC;
    signal base_ddr_addr_BREADY : STD_LOGIC;
    signal base_ddr_addr_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal base_ddr_addr_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal base_ddr_addr_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal ddr_to_axis_reader_base_ddr_addr_m_axi_U_ap_dummy_ce : STD_LOGIC;
    signal indvar_reg_219 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_indvar_reg_219_pp0_it1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_9 : STD_LOGIC;
    signal ap_sig_bdd_185 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal exitcond2_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_194 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal j_reg_231 : STD_LOGIC_VECTOR (12 downto 0);
    signal inner_index_V_2_fu_242_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal inner_index_V_2_reg_509 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_248_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_515 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_216 : BOOLEAN;
    signal i_1_fu_276_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_1_reg_529 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_227 : BOOLEAN;
    signal exitcond1_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_ioackin_base_ddr_addr_ARREADY : STD_LOGIC;
    signal exitcond2_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_exitcond2_reg_543_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_next_fu_347_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal indvar_next_reg_547 : STD_LOGIC_VECTOR (9 downto 0);
    signal base_ddr_addr_addr_read_reg_552 : STD_LOGIC_VECTOR (63 downto 0);
    signal exitcond_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_reg_557 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp1_stg0_fsm_10 : STD_LOGIC;
    signal ap_sig_bdd_256 : BOOLEAN;
    signal ap_reg_ppiten_pp1_it0 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp1_it1 : STD_LOGIC := '0';
    signal ap_reg_ppstg_exitcond_reg_557_pp1_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_ioackin_outStream_V_TREADY : STD_LOGIC;
    signal ap_reg_ppiten_pp1_it2 : STD_LOGIC := '0';
    signal j_1_fu_364_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_6_fu_370_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_reg_566 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_444_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_16_reg_576 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_22_fu_472_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_22_reg_581 : STD_LOGIC_VECTOR (63 downto 0);
    signal offset_fu_503_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_sig_cseq_ST_st16_fsm_11 : STD_LOGIC;
    signal ap_sig_bdd_296 : BOOLEAN;
    signal ap_sig_cseq_ST_st9_fsm_8 : STD_LOGIC;
    signal ap_sig_bdd_303 : BOOLEAN;
    signal buffer_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_ce0 : STD_LOGIC;
    signal buffer_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal buffer_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_ce1 : STD_LOGIC;
    signal buffer_we1 : STD_LOGIC;
    signal buffer_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal offset1_reg_198 : STD_LOGIC_VECTOR (18 downto 0);
    signal i_reg_208 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_phi_fu_223_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_353_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal gepindex2_cast_fu_384_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_fu_282_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_base_ddr_addr_ARREADY : STD_LOGIC := '0';
    signal tmp_3_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_323_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ioackin_outStream_V_TREADY : STD_LOGIC := '0';
    signal tmp_1_fu_254_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_254_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal gepindex_cast_fu_374_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal start_pos_fu_389_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal end_pos_fu_396_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_10_fu_408_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_11_fu_412_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_8_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_426_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_15_fu_438_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_12_fu_416_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_14_fu_432_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_18_fu_460_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_17_fu_452_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_20_fu_468_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_19_fu_478_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_21_fu_483_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_23_fu_487_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_24_fu_493_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_254_p00 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_sig_bdd_348 : BOOLEAN;
    signal ap_sig_bdd_378 : BOOLEAN;

    component ddr_to_axis_reader_buffer IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ddr_to_axis_reader_base_ddr_addr_m_axi IS
    generic (
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_TARGET_ADDR : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    ddr_to_axis_reader_base_ddr_addr_m_axi_U : component ddr_to_axis_reader_base_ddr_addr_m_axi
    generic map (
        USER_DW => 64,
        USER_AW => 32,
        USER_MAXREQS => 5,
        C_M_AXI_ID_WIDTH => C_M_AXI_BASE_DDR_ADDR_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_BASE_DDR_ADDR_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_BASE_DDR_ADDR_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_BASE_DDR_ADDR_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_BASE_DDR_ADDR_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_BASE_DDR_ADDR_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_BASE_DDR_ADDR_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_BASE_DDR_ADDR_BUSER_WIDTH,
        C_TARGET_ADDR => C_M_AXI_BASE_DDR_ADDR_TARGET_ADDR,
        C_USER_VALUE => C_M_AXI_BASE_DDR_ADDR_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_BASE_DDR_ADDR_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_BASE_DDR_ADDR_CACHE_VALUE)
    port map (
        AWVALID => m_axi_base_ddr_addr_AWVALID,
        AWREADY => m_axi_base_ddr_addr_AWREADY,
        AWADDR => m_axi_base_ddr_addr_AWADDR,
        AWID => m_axi_base_ddr_addr_AWID,
        AWLEN => m_axi_base_ddr_addr_AWLEN,
        AWSIZE => m_axi_base_ddr_addr_AWSIZE,
        AWBURST => m_axi_base_ddr_addr_AWBURST,
        AWLOCK => m_axi_base_ddr_addr_AWLOCK,
        AWCACHE => m_axi_base_ddr_addr_AWCACHE,
        AWPROT => m_axi_base_ddr_addr_AWPROT,
        AWQOS => m_axi_base_ddr_addr_AWQOS,
        AWREGION => m_axi_base_ddr_addr_AWREGION,
        AWUSER => m_axi_base_ddr_addr_AWUSER,
        WVALID => m_axi_base_ddr_addr_WVALID,
        WREADY => m_axi_base_ddr_addr_WREADY,
        WDATA => m_axi_base_ddr_addr_WDATA,
        WSTRB => m_axi_base_ddr_addr_WSTRB,
        WLAST => m_axi_base_ddr_addr_WLAST,
        WID => m_axi_base_ddr_addr_WID,
        WUSER => m_axi_base_ddr_addr_WUSER,
        ARVALID => m_axi_base_ddr_addr_ARVALID,
        ARREADY => m_axi_base_ddr_addr_ARREADY,
        ARADDR => m_axi_base_ddr_addr_ARADDR,
        ARID => m_axi_base_ddr_addr_ARID,
        ARLEN => m_axi_base_ddr_addr_ARLEN,
        ARSIZE => m_axi_base_ddr_addr_ARSIZE,
        ARBURST => m_axi_base_ddr_addr_ARBURST,
        ARLOCK => m_axi_base_ddr_addr_ARLOCK,
        ARCACHE => m_axi_base_ddr_addr_ARCACHE,
        ARPROT => m_axi_base_ddr_addr_ARPROT,
        ARQOS => m_axi_base_ddr_addr_ARQOS,
        ARREGION => m_axi_base_ddr_addr_ARREGION,
        ARUSER => m_axi_base_ddr_addr_ARUSER,
        RVALID => m_axi_base_ddr_addr_RVALID,
        RREADY => m_axi_base_ddr_addr_RREADY,
        RDATA => m_axi_base_ddr_addr_RDATA,
        RLAST => m_axi_base_ddr_addr_RLAST,
        RID => m_axi_base_ddr_addr_RID,
        RUSER => m_axi_base_ddr_addr_RUSER,
        RRESP => m_axi_base_ddr_addr_RRESP,
        BVALID => m_axi_base_ddr_addr_BVALID,
        BREADY => m_axi_base_ddr_addr_BREADY,
        BRESP => m_axi_base_ddr_addr_BRESP,
        BID => m_axi_base_ddr_addr_BID,
        BUSER => m_axi_base_ddr_addr_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ddr_to_axis_reader_base_ddr_addr_m_axi_U_ap_dummy_ce,
        I_ARVALID => base_ddr_addr_ARVALID,
        I_ARREADY => base_ddr_addr_ARREADY,
        I_ARADDR => base_ddr_addr_ARADDR,
        I_ARID => base_ddr_addr_ARID,
        I_ARLEN => base_ddr_addr_ARLEN,
        I_ARSIZE => base_ddr_addr_ARSIZE,
        I_ARLOCK => base_ddr_addr_ARLOCK,
        I_ARCACHE => base_ddr_addr_ARCACHE,
        I_ARQOS => base_ddr_addr_ARQOS,
        I_ARPROT => base_ddr_addr_ARPROT,
        I_ARUSER => base_ddr_addr_ARUSER,
        I_ARBURST => base_ddr_addr_ARBURST,
        I_ARREGION => base_ddr_addr_ARREGION,
        I_RVALID => base_ddr_addr_RVALID,
        I_RREADY => base_ddr_addr_RREADY,
        I_RDATA => base_ddr_addr_RDATA,
        I_RID => base_ddr_addr_RID,
        I_RUSER => base_ddr_addr_RUSER,
        I_RRESP => base_ddr_addr_RRESP,
        I_RLAST => base_ddr_addr_RLAST,
        I_AWVALID => base_ddr_addr_AWVALID,
        I_AWREADY => base_ddr_addr_AWREADY,
        I_AWADDR => base_ddr_addr_AWADDR,
        I_AWID => base_ddr_addr_AWID,
        I_AWLEN => base_ddr_addr_AWLEN,
        I_AWSIZE => base_ddr_addr_AWSIZE,
        I_AWLOCK => base_ddr_addr_AWLOCK,
        I_AWCACHE => base_ddr_addr_AWCACHE,
        I_AWQOS => base_ddr_addr_AWQOS,
        I_AWPROT => base_ddr_addr_AWPROT,
        I_AWUSER => base_ddr_addr_AWUSER,
        I_AWBURST => base_ddr_addr_AWBURST,
        I_AWREGION => base_ddr_addr_AWREGION,
        I_WVALID => base_ddr_addr_WVALID,
        I_WREADY => base_ddr_addr_WREADY,
        I_WDATA => base_ddr_addr_WDATA,
        I_WID => base_ddr_addr_WID,
        I_WUSER => base_ddr_addr_WUSER,
        I_WLAST => base_ddr_addr_WLAST,
        I_WSTRB => base_ddr_addr_WSTRB,
        I_BVALID => base_ddr_addr_BVALID,
        I_BREADY => base_ddr_addr_BREADY,
        I_BRESP => base_ddr_addr_BRESP,
        I_BID => base_ddr_addr_BID,
        I_BUSER => base_ddr_addr_BUSER);

    buffer_U : component ddr_to_axis_reader_buffer
    generic map (
        DataWidth => 64,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => buffer_address0,
        ce0 => buffer_ce0,
        q0 => buffer_q0,
        address1 => buffer_address1,
        ce1 => buffer_ce1,
        we1 => buffer_we1,
        d1 => buffer_d1);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_base_ddr_addr_ARREADY assign process. --
    ap_reg_ioackin_base_ddr_addr_ARREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_base_ddr_addr_ARREADY <= ap_const_logic_0;
            else
                if (ap_sig_bdd_348) then
                    if (not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY)))) then 
                        ap_reg_ioackin_base_ddr_addr_ARREADY <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = base_ddr_addr_ARREADY)) then 
                        ap_reg_ioackin_base_ddr_addr_ARREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_outStream_V_TREADY assign process. --
    ap_reg_ioackin_outStream_V_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_outStream_V_TREADY <= ap_const_logic_0;
            else
                if (ap_sig_bdd_378) then
                    if (not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2)))) then 
                        ap_reg_ioackin_outStream_V_TREADY <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = outStream_V_TREADY)) then 
                        ap_reg_ioackin_outStream_V_TREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8)) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (ap_const_lv1_0 = exitcond2_fu_341_p2))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it2 assign process. --
    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8)) then 
                    ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp1_it0 assign process. --
    ap_reg_ppiten_pp1_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and not((ap_const_lv1_0 = exitcond_fu_358_p2)))) then 
                    ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2)))) then 
                    ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp1_it1 assign process. --
    ap_reg_ppiten_pp1_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and (ap_const_lv1_0 = exitcond_fu_358_p2))) then 
                    ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and not((ap_const_lv1_0 = exitcond_fu_358_p2))))) then 
                    ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp1_it2 assign process. --
    ap_reg_ppiten_pp1_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
            else
                if (not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2)))) then 
                    ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2)))) then 
                    ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- frame_count_equals_inner assign process. --
    frame_count_equals_inner_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                frame_count_equals_inner <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))) and not((ap_const_lv1_0 = exitcond1_fu_270_p2)) and not((ap_const_lv1_0 = tmp_4_fu_314_p2)))) then 
                    frame_count_equals_inner <= tmp_5_fu_323_p2;
                end if; 
            end if;
        end if;
    end process;


    -- frame_count_inner assign process. --
    frame_count_inner_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                frame_count_inner <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))) and not((ap_const_lv1_0 = exitcond1_fu_270_p2)))) then 
                    frame_count_inner <= tmp_3_fu_297_p2;
                end if; 
            end if;
        end if;
    end process;


    -- index_old assign process. --
    index_old_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                index_old <= ap_const_lv32_FFFFFFFF;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))) and not((ap_const_lv1_0 = exitcond1_fu_270_p2)))) then 
                    index_old <= tmp_reg_515;
                end if; 
            end if;
        end if;
    end process;


    -- i_reg_208 assign process. --
    i_reg_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st16_fsm_11)) then 
                i_reg_208 <= i_1_reg_529;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                i_reg_208 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    -- indvar_reg_219 assign process. --
    indvar_reg_219_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8)) then 
                indvar_reg_219 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (exitcond2_reg_543 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
                indvar_reg_219 <= indvar_next_reg_547;
            end if; 
        end if;
    end process;

    -- j_reg_231 assign process. --
    j_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2)))) then 
                j_reg_231 <= ap_const_lv13_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and (ap_const_lv1_0 = exitcond_fu_358_p2))) then 
                j_reg_231 <= j_1_fu_364_p2;
            end if; 
        end if;
    end process;

    -- offset1_reg_198 assign process. --
    offset1_reg_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st16_fsm_11)) then 
                offset1_reg_198 <= offset_fu_503_p2;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                offset1_reg_198 <= tmp_1_fu_254_p2(21 downto 3);
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                ap_reg_ppstg_exitcond2_reg_543_pp0_it1 <= exitcond2_reg_543;
                ap_reg_ppstg_indvar_reg_219_pp0_it1 <= indvar_reg_219;
                exitcond2_reg_543 <= exitcond2_fu_341_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))))) then
                ap_reg_ppstg_exitcond_reg_557_pp1_it1 <= exitcond_reg_557;
                exitcond_reg_557 <= exitcond_fu_358_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (exitcond2_reg_543 = ap_const_lv1_0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                base_ddr_addr_addr_read_reg_552 <= base_ddr_addr_RDATA;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))))) then
                i_1_reg_529 <= i_1_fu_276_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                indvar_next_reg_547 <= indvar_next_fu_347_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then
                inner_index_V_2_reg_509 <= inner_index_V_2_fu_242_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and (ap_const_lv1_0 = exitcond_reg_557))) then
                    tmp_16_reg_576(6 downto 1) <= tmp_16_fu_444_p3(6 downto 1);
                tmp_22_reg_581 <= tmp_22_fu_472_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and (ap_const_lv1_0 = exitcond_fu_358_p2))) then
                tmp_6_reg_566 <= tmp_6_fu_370_p1;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                    tmp_reg_515(2 downto 0) <= tmp_fu_248_p1(2 downto 0);
            end if;
        end if;
    end process;
    tmp_reg_515(31 downto 3) <= "00000000000000000000000000000";
    tmp_16_reg_576(0) <= '1';

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_sig_bdd_194, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it2, exitcond1_fu_270_p2, ap_sig_ioackin_base_ddr_addr_ARREADY, exitcond2_fu_341_p2, exitcond_fu_358_p2, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, ap_reg_ppstg_exitcond_reg_557_pp1_it1, ap_sig_ioackin_outStream_V_TREADY, ap_reg_ppiten_pp1_it2)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st3_fsm_2 => 
                if ((not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))) and not((ap_const_lv1_0 = exitcond1_fu_270_p2)))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                elsif (((ap_const_lv1_0 = exitcond1_fu_270_p2) and not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st6_fsm_5;
            when ap_ST_st6_fsm_5 => 
                ap_NS_fsm <= ap_ST_st7_fsm_6;
            when ap_ST_st7_fsm_6 => 
                ap_NS_fsm <= ap_ST_st8_fsm_7;
            when ap_ST_st8_fsm_7 => 
                ap_NS_fsm <= ap_ST_st9_fsm_8;
            when ap_ST_st9_fsm_8 => 
                ap_NS_fsm <= ap_ST_pp0_stg0_fsm_9;
            when ap_ST_pp0_stg0_fsm_9 => 
                if ((not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_9;
                elsif ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((ap_const_lv1_0 = exitcond2_fu_341_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_10;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_9;
                end if;
            when ap_ST_pp1_stg0_fsm_10 => 
                if ((not(((ap_const_logic_1 = ap_reg_ppiten_pp1_it2) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and not((ap_const_logic_1 = ap_reg_ppiten_pp1_it1)))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and not((ap_const_lv1_0 = exitcond_fu_358_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp1_it1)))))) then
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_10;
                elsif ((((ap_const_logic_1 = ap_reg_ppiten_pp1_it2) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and not((ap_const_logic_1 = ap_reg_ppiten_pp1_it1))) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))) and not((ap_const_lv1_0 = exitcond_fu_358_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp1_it1))))) then
                    ap_NS_fsm <= ap_ST_st16_fsm_11;
                else
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_10;
                end if;
            when ap_ST_st16_fsm_11 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_270_p2, ap_sig_ioackin_base_ddr_addr_ARREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))) and not((ap_const_lv1_0 = exitcond1_fu_270_p2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_270_p2, ap_sig_ioackin_base_ddr_addr_ARREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not(((ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_sig_ioackin_base_ddr_addr_ARREADY))) and not((ap_const_lv1_0 = exitcond1_fu_270_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    -- ap_sig_bdd_185 assign process. --
    ap_sig_bdd_185_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_185 <= (ap_const_lv1_1 = ap_CS_fsm(9 downto 9));
    end process;


    -- ap_sig_bdd_194 assign process. --
    ap_sig_bdd_194_assign_proc : process(base_ddr_addr_RVALID, exitcond2_reg_543)
    begin
                ap_sig_bdd_194 <= ((base_ddr_addr_RVALID = ap_const_logic_0) and (exitcond2_reg_543 = ap_const_lv1_0));
    end process;


    -- ap_sig_bdd_216 assign process. --
    ap_sig_bdd_216_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_216 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_bdd_227 assign process. --
    ap_sig_bdd_227_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_227 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_256 assign process. --
    ap_sig_bdd_256_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_256 <= (ap_const_lv1_1 = ap_CS_fsm(10 downto 10));
    end process;


    -- ap_sig_bdd_296 assign process. --
    ap_sig_bdd_296_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_296 <= (ap_const_lv1_1 = ap_CS_fsm(11 downto 11));
    end process;


    -- ap_sig_bdd_30 assign process. --
    ap_sig_bdd_30_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_30 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_303 assign process. --
    ap_sig_bdd_303_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_303 <= (ap_const_lv1_1 = ap_CS_fsm(8 downto 8));
    end process;


    -- ap_sig_bdd_348 assign process. --
    ap_sig_bdd_348_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_270_p2)
    begin
                ap_sig_bdd_348 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_270_p2));
    end process;


    -- ap_sig_bdd_378 assign process. --
    ap_sig_bdd_378_assign_proc : process(ap_reg_ppstg_exitcond_reg_557_pp1_it1, ap_reg_ppiten_pp1_it2)
    begin
                ap_sig_bdd_378 <= ((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2));
    end process;


    -- ap_sig_cseq_ST_pp0_stg0_fsm_9 assign process. --
    ap_sig_cseq_ST_pp0_stg0_fsm_9_assign_proc : process(ap_sig_bdd_185)
    begin
        if (ap_sig_bdd_185) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_9 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_9 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_pp1_stg0_fsm_10 assign process. --
    ap_sig_cseq_ST_pp1_stg0_fsm_10_assign_proc : process(ap_sig_bdd_256)
    begin
        if (ap_sig_bdd_256) then 
            ap_sig_cseq_ST_pp1_stg0_fsm_10 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp1_stg0_fsm_10 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st16_fsm_11 assign process. --
    ap_sig_cseq_ST_st16_fsm_11_assign_proc : process(ap_sig_bdd_296)
    begin
        if (ap_sig_bdd_296) then 
            ap_sig_cseq_ST_st16_fsm_11 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st16_fsm_11 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_30)
    begin
        if (ap_sig_bdd_30) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_216)
    begin
        if (ap_sig_bdd_216) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st3_fsm_2 assign process. --
    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_bdd_227)
    begin
        if (ap_sig_bdd_227) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st9_fsm_8 assign process. --
    ap_sig_cseq_ST_st9_fsm_8_assign_proc : process(ap_sig_bdd_303)
    begin
        if (ap_sig_bdd_303) then 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ioackin_base_ddr_addr_ARREADY assign process. --
    ap_sig_ioackin_base_ddr_addr_ARREADY_assign_proc : process(base_ddr_addr_ARREADY, ap_reg_ioackin_base_ddr_addr_ARREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_base_ddr_addr_ARREADY)) then 
            ap_sig_ioackin_base_ddr_addr_ARREADY <= base_ddr_addr_ARREADY;
        else 
            ap_sig_ioackin_base_ddr_addr_ARREADY <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ioackin_outStream_V_TREADY assign process. --
    ap_sig_ioackin_outStream_V_TREADY_assign_proc : process(outStream_V_TREADY, ap_reg_ioackin_outStream_V_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_outStream_V_TREADY)) then 
            ap_sig_ioackin_outStream_V_TREADY <= outStream_V_TREADY;
        else 
            ap_sig_ioackin_outStream_V_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    base_ddr_addr_ARADDR <= tmp_2_fu_282_p1(32 - 1 downto 0);
    base_ddr_addr_ARBURST <= ap_const_lv2_0;
    base_ddr_addr_ARCACHE <= ap_const_lv4_0;
    base_ddr_addr_ARID <= ap_const_lv1_0;
    base_ddr_addr_ARLEN <= ap_const_lv32_200;
    base_ddr_addr_ARLOCK <= ap_const_lv2_0;
    base_ddr_addr_ARPROT <= ap_const_lv3_0;
    base_ddr_addr_ARQOS <= ap_const_lv4_0;
    base_ddr_addr_ARREGION <= ap_const_lv4_0;
    base_ddr_addr_ARSIZE <= ap_const_lv3_0;
    base_ddr_addr_ARUSER <= ap_const_lv1_0;

    -- base_ddr_addr_ARVALID assign process. --
    base_ddr_addr_ARVALID_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_270_p2, ap_reg_ioackin_base_ddr_addr_ARREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_270_p2) and (ap_const_logic_0 = ap_reg_ioackin_base_ddr_addr_ARREADY))) then 
            base_ddr_addr_ARVALID <= ap_const_logic_1;
        else 
            base_ddr_addr_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    base_ddr_addr_AWADDR <= ap_const_lv32_0;
    base_ddr_addr_AWBURST <= ap_const_lv2_0;
    base_ddr_addr_AWCACHE <= ap_const_lv4_0;
    base_ddr_addr_AWID <= ap_const_lv1_0;
    base_ddr_addr_AWLEN <= ap_const_lv32_0;
    base_ddr_addr_AWLOCK <= ap_const_lv2_0;
    base_ddr_addr_AWPROT <= ap_const_lv3_0;
    base_ddr_addr_AWQOS <= ap_const_lv4_0;
    base_ddr_addr_AWREGION <= ap_const_lv4_0;
    base_ddr_addr_AWSIZE <= ap_const_lv3_0;
    base_ddr_addr_AWUSER <= ap_const_lv1_0;
    base_ddr_addr_AWVALID <= ap_const_logic_0;
    base_ddr_addr_BREADY <= ap_const_logic_0;

    -- base_ddr_addr_RREADY assign process. --
    base_ddr_addr_RREADY_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_9, exitcond2_reg_543, ap_sig_bdd_194, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (exitcond2_reg_543 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
            base_ddr_addr_RREADY <= ap_const_logic_1;
        else 
            base_ddr_addr_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    base_ddr_addr_WDATA <= ap_const_lv64_0;
    base_ddr_addr_WID <= ap_const_lv1_0;
    base_ddr_addr_WLAST <= ap_const_logic_0;
    base_ddr_addr_WSTRB <= ap_const_lv8_0;
    base_ddr_addr_WUSER <= ap_const_lv1_0;
    base_ddr_addr_WVALID <= ap_const_logic_0;
    buffer_address0 <= gepindex2_cast_fu_384_p1(9 - 1 downto 0);
    buffer_address1 <= tmp_7_fu_353_p1(9 - 1 downto 0);

    -- buffer_ce0 assign process. --
    buffer_ce0_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_10, ap_reg_ppiten_pp1_it0, ap_reg_ppstg_exitcond_reg_557_pp1_it1, ap_sig_ioackin_outStream_V_TREADY, ap_reg_ppiten_pp1_it2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_10) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not(((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_0 = ap_sig_ioackin_outStream_V_TREADY) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2))))) then 
            buffer_ce0 <= ap_const_logic_1;
        else 
            buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- buffer_ce1 assign process. --
    buffer_ce1_assign_proc : process(ap_sig_bdd_194, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it2)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
            buffer_ce1 <= ap_const_logic_1;
        else 
            buffer_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    buffer_d1 <= base_ddr_addr_addr_read_reg_552;

    -- buffer_we1 assign process. --
    buffer_we1_assign_proc : process(ap_sig_bdd_194, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it2, ap_reg_ppstg_exitcond2_reg_543_pp0_it1)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_sig_bdd_194 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond2_reg_543_pp0_it1)))) then 
            buffer_we1 <= ap_const_logic_1;
        else 
            buffer_we1 <= ap_const_logic_0;
        end if; 
    end process;

    ddr_to_axis_reader_base_ddr_addr_m_axi_U_ap_dummy_ce <= ap_const_logic_1;
    end_pos_fu_396_p2 <= (start_pos_fu_389_p3 or ap_const_lv6_7);
    exitcond1_fu_270_p2 <= "1" when (i_reg_208 = ap_const_lv7_4B) else "0";
    exitcond2_fu_341_p2 <= "1" when (indvar_phi_fu_223_p4 = ap_const_lv10_200) else "0";
    exitcond_fu_358_p2 <= "1" when (j_reg_231 = ap_const_lv13_1000) else "0";
    frame_count <= std_logic_vector(unsigned(frame_count_inner) + unsigned(ap_const_lv32_1));
    frame_count_equals <= std_logic_vector(unsigned(frame_count_equals_inner) + unsigned(ap_const_lv32_1));
    gepindex2_cast_fu_384_p1 <= std_logic_vector(resize(unsigned(gepindex_cast_fu_374_p4),64));
    gepindex_cast_fu_374_p4 <= j_reg_231(11 downto 3);
    i_1_fu_276_p2 <= std_logic_vector(unsigned(i_reg_208) + unsigned(ap_const_lv7_1));
    indvar_next_fu_347_p2 <= std_logic_vector(unsigned(indvar_phi_fu_223_p4) + unsigned(ap_const_lv10_1));

    -- indvar_phi_fu_223_p4 assign process. --
    indvar_phi_fu_223_p4_assign_proc : process(indvar_reg_219, ap_sig_cseq_ST_pp0_stg0_fsm_9, exitcond2_reg_543, ap_reg_ppiten_pp0_it1, indvar_next_reg_547)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_9) and (exitcond2_reg_543 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            indvar_phi_fu_223_p4 <= indvar_next_reg_547;
        else 
            indvar_phi_fu_223_p4 <= indvar_reg_219;
        end if; 
    end process;

    inner_index_V_2_fu_242_p2 <= std_logic_vector(unsigned(frame_index_V) + unsigned(ap_const_lv3_7));
    j_1_fu_364_p2 <= std_logic_vector(unsigned(j_reg_231) + unsigned(ap_const_lv13_1));
    offset_fu_503_p2 <= std_logic_vector(unsigned(offset1_reg_198) + unsigned(ap_const_lv19_200));
    outStream_V_TDATA <= tmp_24_fu_493_p2(8 - 1 downto 0);

    -- outStream_V_TVALID assign process. --
    outStream_V_TVALID_assign_proc : process(ap_reg_ppstg_exitcond_reg_557_pp1_it1, ap_reg_ppiten_pp1_it2, ap_reg_ioackin_outStream_V_TREADY)
    begin
        if (((ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_557_pp1_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it2) and (ap_const_logic_0 = ap_reg_ioackin_outStream_V_TREADY))) then 
            outStream_V_TVALID <= ap_const_logic_1;
        else 
            outStream_V_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    start_pos_fu_389_p3 <= (tmp_6_reg_566 & ap_const_lv3_0);
    tmp_10_fu_408_p1 <= std_logic_vector(resize(unsigned(start_pos_fu_389_p3),7));
    tmp_11_fu_412_p1 <= std_logic_vector(resize(unsigned(end_pos_fu_396_p2),7));
    
    tmp_12_fu_416_p4_proc : process(buffer_q0)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_12_fu_416_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_3F(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_0(6 - 1 downto 0);
        v0_cpy := buffer_q0;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_0(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3F(6-1 downto 0)));
            for tmp_12_fu_416_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_12_fu_416_p4_i) := buffer_q0(64-1-tmp_12_fu_416_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy),to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_12_fu_416_p4 <= resvalue(64-1 downto 0);
    end process;

    tmp_13_fu_426_p2 <= std_logic_vector(unsigned(tmp_10_fu_408_p1) - unsigned(tmp_11_fu_412_p1));
    tmp_14_fu_432_p2 <= (tmp_10_fu_408_p1 xor ap_const_lv7_3F);
    tmp_15_fu_438_p2 <= std_logic_vector(unsigned(tmp_11_fu_412_p1) - unsigned(tmp_10_fu_408_p1));
    tmp_16_fu_444_p3 <= 
        tmp_13_fu_426_p2 when (tmp_8_fu_402_p2(0) = '1') else 
        tmp_15_fu_438_p2;
    tmp_17_fu_452_p3 <= 
        tmp_12_fu_416_p4 when (tmp_8_fu_402_p2(0) = '1') else 
        buffer_q0;
    tmp_18_fu_460_p3 <= 
        tmp_14_fu_432_p2 when (tmp_8_fu_402_p2(0) = '1') else 
        tmp_10_fu_408_p1;
    tmp_19_fu_478_p2 <= std_logic_vector(unsigned(ap_const_lv7_3F) - unsigned(tmp_16_reg_576));
    tmp_1_fu_254_p0 <= tmp_1_fu_254_p00(3 - 1 downto 0);
    tmp_1_fu_254_p00 <= std_logic_vector(resize(unsigned(inner_index_V_2_reg_509),22));
    tmp_1_fu_254_p2 <= std_logic_vector(resize(unsigned(tmp_1_fu_254_p0) * unsigned(ap_const_lv22_4B000), 22));
    tmp_20_fu_468_p1 <= std_logic_vector(resize(unsigned(tmp_18_fu_460_p3),64));
    tmp_21_fu_483_p1 <= std_logic_vector(resize(unsigned(tmp_19_fu_478_p2),64));
    tmp_22_fu_472_p2 <= std_logic_vector(shift_right(unsigned(tmp_17_fu_452_p3),to_integer(unsigned('0' & tmp_20_fu_468_p1(31-1 downto 0)))));
    tmp_23_fu_487_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv64_FFFFFFFFFFFFFFFF),to_integer(unsigned('0' & tmp_21_fu_483_p1(31-1 downto 0)))));
    tmp_24_fu_493_p2 <= (tmp_22_reg_581 and tmp_23_fu_487_p2);
    tmp_2_fu_282_p1 <= std_logic_vector(resize(unsigned(offset1_reg_198),64));
    tmp_3_fu_297_p2 <= std_logic_vector(unsigned(frame_count_inner) + unsigned(ap_const_lv32_1));
    tmp_4_fu_314_p2 <= "1" when (tmp_reg_515 = index_old) else "0";
    tmp_5_fu_323_p2 <= std_logic_vector(unsigned(frame_count_equals_inner) + unsigned(ap_const_lv32_1));
    tmp_6_fu_370_p1 <= j_reg_231(3 - 1 downto 0);
    tmp_7_fu_353_p1 <= std_logic_vector(resize(unsigned(ap_reg_ppstg_indvar_reg_219_pp0_it1),64));
    tmp_8_fu_402_p2 <= "1" when (unsigned(start_pos_fu_389_p3) > unsigned(end_pos_fu_396_p2)) else "0";
    tmp_fu_248_p1 <= std_logic_vector(resize(unsigned(inner_index_V_2_reg_509),32));
end behav;
