set_property PACKAGE_PIN AB19 [get_ports {B_V[3]}]
set_property PACKAGE_PIN AB20 [get_ports {B_V[2]}]
set_property PACKAGE_PIN Y20 [get_ports {B_V[1]}]
set_property PACKAGE_PIN Y21 [get_ports {B_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_V[0]}]
set_property PACKAGE_PIN H22 [get_ports ext_reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in]
set_property PACKAGE_PIN AA21 [get_ports {G_V[3]}]
set_property PACKAGE_PIN AB21 [get_ports {G_V[2]}]
set_property PACKAGE_PIN AA22 [get_ports {G_V[1]}]
set_property PACKAGE_PIN AB22 [get_ports {G_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_V[0]}]
set_property PACKAGE_PIN AA19 [get_ports {H_SYNC_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_SYNC_V[0]}]
set_property PACKAGE_PIN V18 [get_ports {R_V[3]}]
set_property PACKAGE_PIN V19 [get_ports {R_V[2]}]
set_property PACKAGE_PIN U20 [get_ports {R_V[1]}]
set_property PACKAGE_PIN V20 [get_ports {R_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_V[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_V[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_V[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_V[0]}]
set_property PACKAGE_PIN F22 [get_ports {selftest[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {selftest[0]}]
set_property PACKAGE_PIN Y19 [get_ports {V_SYNC_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {V_SYNC_V[0]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets PCLK_IBUF]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[0]}]
set_property PACKAGE_PIN AA8 [get_ports {data_in_V[7]}]
set_property PACKAGE_PIN AA9 [get_ports {data_in_V[6]}]
set_property PACKAGE_PIN AB9 [get_ports {data_in_V[5]}]
set_property PACKAGE_PIN Y10 [get_ports {data_in_V[4]}]
set_property PACKAGE_PIN AB10 [get_ports {data_in_V[3]}]
set_property PACKAGE_PIN AA11 [get_ports {data_in_V[2]}]
set_property PACKAGE_PIN AB11 [get_ports {data_in_V[1]}]
set_property PACKAGE_PIN Y11 [get_ports {data_in_V[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {href_V[0]}]
set_property PACKAGE_PIN V10 [get_ports {href_V[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports PCLK]
set_property PACKAGE_PIN V12 [get_ports {OV7670_RESET[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {OV7670_RESET[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {vsync_V[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports XCLK]
set_property PACKAGE_PIN W11 [get_ports XCLK]
set_property PACKAGE_PIN W10 [get_ports PCLK]
set_property PACKAGE_PIN V9 [get_ports {vsync_V[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {id_filter[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {id_filter[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {id_filter[0]}]
set_property PACKAGE_PIN M15 [get_ports {id_filter[2]}]
set_property PACKAGE_PIN H17 [get_ports {id_filter[1]}]
set_property PACKAGE_PIN H18 [get_ports {id_filter[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports reset_sw]
set_property PACKAGE_PIN G22 [get_ports reset_sw]

set_property PACKAGE_PIN T22 [get_ports {LED_FRAME_VALID[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_FRAME_VALID[0]}]


set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TREADY]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[0]} {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[1]} {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[2]} {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[3]} {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[4]} {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[5]} {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[6]} {design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TDATA[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/OV7670_GRAYSCALE_TO_AXIS/ddr_to_axis_reader_SD_0_outStream_V_TREADY]]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/OV7670_GRAYSCALE_TO_AXIS/outStream_V_TVALID]]




set_property PACKAGE_PIN F21 [get_ports {SWITCH_SD_STREAM[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH_SD_STREAM[0]}]
